### ISSUE TITLE
sendMessage method makes parseInt error

### ISSUE THREAD

**Issue by kaosf** [jenkinsci/chatwork-plugin#16]
```
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:417)
	at java.lang.Integer.parseInt(Integer.java:499)
	at com.vexus2.jenkins.chatwork.jenkinschatworkplugin.ChatworkClient.sendMessage(ChatworkClient.java:43)
	at com.vexus2.jenkins.chatwork.jenkinschatworkplugin.ChatworkPublisher.perform(ChatworkPublisher.java:86)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
	at hudson.model.Run.execute(Run.java:1743)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
```

https://github.com/jenkinsci/chatwork-plugin/blob/ce0d967880b97e4e788633993fe4030e46406c45/src/main/java/com/vexus2/jenkins/chatwork/jenkinschatworkplugin/ChatworkClient.java#L40-L45

プロキシ機能を使ってないサーバで確認されました．プロキシ機能を使ってないのに使う方に分岐しているのが根本原因かと思います．

**Comment by sue445** [comment]
設定どうなってるでしょうか？

プロキシ使わない場合は明示的に Proxy serverに `NOPROXY` セットしてください

![ap23nq](https://cloud.githubusercontent.com/assets/608755/6483191/7d129594-c2b1-11e4-9cb3-89a249958db5.png)

**Comment by kaosf** [comment]
確認します

**Comment by sue445** [comment]
NOPROXYの前後に余計な空白ついてないでしょうか？

**Comment by kaosf** [comment]
ついて無かったですね．どうにかこの `this.proxySv` を見ることが出来れば良いのですが．

**Comment by kaosf** [comment]
面白いことが起こりました．

`/var/lib/jenkins/com.vexus2.jenkins.chatwork.jenkinschatworkplugin.ChatworkPublisher.xml` の内容がですね，最初は

```
<?xml version='1.0' encoding='UTF-8'?>
<com.vexus2.jenkins.chatwork.jenkinschatworkplugin.ChatworkPublisher_-DescriptorImpl plugin="chatwork@0.6.2">
  <apikey>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</apikey>
</com.vexus2.jenkins.chatwork.jenkinschatworkplugin.ChatworkPublisher_-DescriptorImpl>
```

だったので，怪しく思って一旦何もせずに設定を「保存」してみたら，以下のように変わりました．

```
<?xml version='1.0' encoding='UTF-8'?>
<com.vexus2.jenkins.chatwork.jenkinschatworkplugin.ChatworkPublisher_-DescriptorImpl plugin="chatwork@0.6.2">
  <apikey>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</apikey>
  <proxysv>NOPROXY</proxysv>
  <proxyport></proxyport>
</com.vexus2.jenkins.chatwork.jenkinschatworkplugin.ChatworkPublisher_-DescriptorImpl>
```

**Comment by kaosf** [comment]
で，直りました．どうして `<proxysv></proxysv>` と `<proxyport></proxyport>` が無い設定ファイルが使われていたのかわからないままですが，とりあえず閉じて起きます．

**Comment by kaosf** [comment]
プラグインのバージョンを 0.3 から 0.6 に確か一気に上げた記憶がありますが，そういうのが影響しているかも…？

**Comment by sue445** [comment]
[![LGTM](http://www.lgtm.in/p/gatHPxdOp)](http://www.lgtm.in/i/gatHPxdOp)

**Comment by sue445** [comment]
> どうして <proxysv></proxysv> と <proxyport></proxyport> が無い設定ファイルが使われていたのか

> プラグインのバージョンを 0.3 から 0.6 に確か一気に上げた記憶がありますが，そういうのが影響しているかも…？

0.3で保存された設定だと `proxysv` と `proxyport` は存在しないですね

設定保存時にディスクへの書き込みがうまくいっていなかった可能性はあります

**Comment by sue445** [comment]
@kaosf see #18

**Comment by kaosf** [comment]
@sue445 I've seen it. thx
